### ISSUE TITLE
tf variable assigned to wrong attribute

### ISSUE THREAD

**Issue by miklosbarabasForm3** [cloudworkz/cortex-ops#4]
Hi

I was having a look at  your repo as an example and I bumped into this. I though it might be worthy to mention, just to avoid any possible headache it might cause :)

https://github.com/cloudworkz/cortex-ops/blob/b1988eb75a59b46f108e37d5dd185061199e78e9/deployment/modules/cortex/ingester.tf#L235

**Comment by weeco** [comment]
Hey,
that's definetely wrong. Thank you for letting me know. I am in the process of replacing the terraform files with Kubernetes manifests (see branch) which will ultimately fix this as well. Until then I leave this issue opened.
